### ISSUE TITLE
1.3.0 update - cannot find module

### ISSUE THREAD

**Issue by chrisblossom** [liady/webpack-node-externals#5]
After updating from 1.2.0 to 1.3.0 I am getting the following error:

```js
Error: Cannot find module '/Users/chris/app/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style!css!postcss!resolve-url!sass?sourceMap!./lib/bootstrap.styles.loader.js!./no-op.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (webpack:///./no-op.js":1:1)
    at __webpack_require__ (webpack:///webpack/bootstrap ffe52b1d2cc71d90e522:19:1)
    at Object.module.exports.module.exports.forcePointer (webpack:///./~/bootstrap-loader/no-op.js:1:1)
    at __webpack_require__ (webpack:///webpack/bootstrap ffe52b1d2cc71d90e522:19:1)
    at Object.<anonymous> (webpack:///./~/bootstrap-loader/extractStyles.js:1:1)
    at __webpack_require__ (webpack:///webpack/bootstrap ffe52b1d2cc71d90e522:19:1)
```

Ideas? Thank you!

**Comment by liady** [comment]
Hey, seems like the latest absolute path support breaks this case. I published 1.3.1, it is now optional and hidden behind a flag.
Let me know if it solves your case

**Comment by chrisblossom** [comment]
1.3.1 works now. Thank you for the quick fix!
