### ISSUE TITLE
After upgrading from version 1.6.0 to 1.7.1 webpack fires an error stating it can't find ./utils

### ISSUE THREAD

**Issue by cramhead** [liady/webpack-node-externals#48]
Thanks for making a great plugin. 

Rolling back to version 1.6.0 and everything works fine. I'm using webpack 4.4.1. 

My config is 
```js
const nodeExternals = require('webpack-node-externals')

module.exports = {
  target: 'node',
  externals: [nodeExternals()]
};
```
I see that the there is a new `utils.js` file in the project. I expect that could be the issue.
$ webpack --mode development
/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-cli/bin/webpack.js:242
                                throw err;
                                ^

Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-node-externals/index.js:1:75)
    at Module._compile (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/d0c/Projects/NODE/express_es2015_webpack/webpack.config.js:1:85)
    at Module._compile (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-cli/bin/webpack.js:239:39)
    at Object.parse (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/yargs/yargs.js:543:18)
    at /Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/d0c/Projects/NODE/express_es2015_webpack/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:649:30)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c webpack --mode development
Directory: /Users/d0c/Projects/NODE/express_es2015_webpack
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/d0c/Projects/NODE/express_es2015_webpack/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liady** [comment]
Correct. Fixed in `1.7.2`. Thanks!
